package com.embassyapp.spring.controller;

import org.springframework.ui.Model;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.embassyapp.spring.model.User;

@RestController
public class RestControler {

	@RequestMapping(value = "/getallUsers", method = RequestMethod.GET)
	public String user(@Validated User user, Model model) {
		
		String returnDate="[\r\n"
				+ "{\"id\":1, \"name\":\"Tiger Nixon\", \"position\":\"System Architect\", \"office\":\"Edinburgh\", \"extension\":\"5421\", \"startDate\":\"2011/04/25\", \"salary\":\"Tiger Nixon\"},\r\n"
				+ "{\"id\":2, \"name\":\"Garrett Winters\", \"position\":\"Accountant\", \"office\":\"Tokyo\", \"extension\":\"8422\", \"startDate\":\"2011/07/25\", \"salary\":\"Garrett Winters\"},\r\n"
				+ "{\"id\":3, \"name\":\"Ashton Cox\", \"position\":\"Junior Technical Author\", \"office\":\"San Francisco\", \"extension\":\"1562\", \"startDate\":\"2009/01/12\", \"salary\":\"Ashton Cox\"},\r\n"
				+ "{\"id\":4, \"name\":\"Cedric Kelly\", \"position\":\"Senior Javascript Developer\", \"office\":\"Edinburgh\", \"extension\":\"6224\", \"startDate\":\"2012/03/29\", \"salary\":\"Cedric Kelly\"},\r\n"
				+ "{\"id\":5, \"name\":\"Airi Satou\", \"position\":\"Accountant\", \"office\":\"Tokyo\", \"extension\":\"5407\", \"startDate\":\"2008/11/28\", \"salary\":\"Airi Satou\"},\r\n"
				+ "{\"id\":6, \"name\":\"Brielle Williamson\", \"position\":\"Integration Specialist\", \"office\":\"New York\", \"extension\":\"4804\", \"startDate\":\"2012/12/02\", \"salary\":\"Brielle Williamson\"},\r\n"
				+ "{\"id\":7, \"name\":\"Herrod Chandler\", \"position\":\"Sales Assistant\", \"office\":\"San Francisco\", \"extension\":\"9608\", \"startDate\":\"2012/08/06\", \"salary\":\"Herrod Chandler\"},\r\n"
				+ "{\"id\":8, \"name\":\"Rhona Davidson\", \"position\":\"Integration Specialist\", \"office\":\"Tokyo\", \"extension\":\"6200\", \"startDate\":\"2010/10/14\", \"salary\":\"Rhona Davidson\"},\r\n"
				+ "{\"id\":9, \"name\":\"Colleen Hurst\", \"position\":\"Javascript Developer\", \"office\":\"San Francisco\", \"extension\":\"2360\", \"startDate\":\"2009/09/15\", \"salary\":\"Colleen Hurst\"},\r\n"
				+ "{\"id\":10, \"name\":\"Sonya Frost\", \"position\":\"Software Engineer\", \"office\":\"Edinburgh\", \"extension\":\"1667\", \"startDate\":\"2008/12/13\", \"salary\":\"Sonya Frost\"},\r\n"
				+ "{\"id\":11, \"name\":\"Jena Gaines\", \"position\":\"Office Manager\", \"office\":\"London\", \"extension\":\"3814\", \"startDate\":\"2008/12/19\", \"salary\":\"Jena Gaines\"},\r\n"
				+ "{\"id\":12, \"name\":\"Quinn Flynn\", \"position\":\"Support Lead\", \"office\":\"Edinburgh\", \"extension\":\"9497\", \"startDate\":\"2013/03/03\", \"salary\":\"Quinn Flynn\"},\r\n"
				+ "{\"id\":13, \"name\":\"Charde Marshall\", \"position\":\"Regional Director\", \"office\":\"San Francisco\", \"extension\":\"6741\", \"startDate\":\"2008/10/16\", \"salary\":\"Charde Marshall\"},\r\n"
				+ "{\"id\":14, \"name\":\"Haley Kennedy\", \"position\":\"Senior Marketing Designer\", \"office\":\"London\", \"extension\":\"3597\", \"startDate\":\"2012/12/18\", \"salary\":\"Haley Kennedy\"},\r\n"
				+ "{\"id\":15, \"name\":\"Tatyana Fitzpatrick\", \"position\":\"Regional Director\", \"office\":\"London\", \"extension\":\"1965\", \"startDate\":\"2010/03/17\", \"salary\":\"Tatyana Fitzpatrick\"},\r\n"
				+ "{\"id\":16, \"name\":\"Michael Silva\", \"position\":\"Marketing Designer\", \"office\":\"London\", \"extension\":\"1581\", \"startDate\":\"2012/11/27\", \"salary\":\"Michael Silva\"},\r\n"
				+ "{\"id\":17, \"name\":\"Paul Byrd\", \"position\":\"Chief Financial Officer (CFO)\", \"office\":\"New York\", \"extension\":\"3059\", \"startDate\":\"2010/06/09\", \"salary\":\"Paul Byrd\"},\r\n"
				+ "{\"id\":18, \"name\":\"Gloria Little\", \"position\":\"Systems Administrator\", \"office\":\"New York\", \"extension\":\"1721\", \"startDate\":\"2009/04/10\", \"salary\":\"Gloria Little\"},\r\n"
				+ "{\"id\":19, \"name\":\"Bradley Greer\", \"position\":\"Software Engineer\", \"office\":\"London\", \"extension\":\"2558\", \"startDate\":\"2012/10/13\", \"salary\":\"Bradley Greer\"},\r\n"
				+ "{\"id\":20, \"name\":\"Dai Rios\", \"position\":\"Personnel Lead\", \"office\":\"Edinburgh\", \"extension\":\"2290\", \"startDate\":\"2012/09/26\", \"salary\":\"Dai Rios\"},\r\n"
				+ "{\"id\":21, \"name\":\"Jenette Caldwell\", \"position\":\"Development Lead\", \"office\":\"New York\", \"extension\":\"1937\", \"startDate\":\"2011/09/03\", \"salary\":\"Jenette Caldwell\"},\r\n"
				+ "{\"id\":22, \"name\":\"Yuri Berry\", \"position\":\"Chief Marketing Officer (CMO)\", \"office\":\"New York\", \"extension\":\"6154\", \"startDate\":\"2009/06/25\", \"salary\":\"Yuri Berry\"},\r\n"
				+ "{\"id\":23, \"name\":\"Caesar Vance\", \"position\":\"Pre-Sales Support\", \"office\":\"New York\", \"extension\":\"8330\", \"startDate\":\"2011/12/12\", \"salary\":\"Caesar Vance\"},\r\n"
				+ "{\"id\":24, \"name\":\"Doris Wilder\", \"position\":\"Sales Assistant\", \"office\":\"Sidney\", \"extension\":\"3023\", \"startDate\":\"2010/09/20\", \"salary\":\"Doris Wilder\"},\r\n"
				+ "{\"id\":25, \"name\":\"Angelica Ramos\", \"position\":\"Chief Executive Officer (CEO)\", \"office\":\"London\", \"extension\":\"5797\", \"startDate\":\"2009/10/09\", \"salary\":\"Angelica Ramos\"},\r\n"
				+ "{\"id\":26, \"name\":\"Gavin Joyce\", \"position\":\"Developer\", \"office\":\"Edinburgh\", \"extension\":\"8822\", \"startDate\":\"2010/12/22\", \"salary\":\"Gavin Joyce\"},\r\n"
				+ "{\"id\":27, \"name\":\"Jennifer Chang\", \"position\":\"Regional Director\", \"office\":\"Singapore\", \"extension\":\"9239\", \"startDate\":\"2010/11/14\", \"salary\":\"Jennifer Chang\"},\r\n"
				+ "{\"id\":28, \"name\":\"Brenden Wagner\", \"position\":\"Software Engineer\", \"office\":\"San Francisco\", \"extension\":\"1314\", \"startDate\":\"2011/06/07\", \"salary\":\"Brenden Wagner\"},\r\n"
				+ "{\"id\":29, \"name\":\"Fiona Green\", \"position\":\"Chief Operating Officer (COO)\", \"office\":\"San Francisco\", \"extension\":\"2947\", \"startDate\":\"2010/03/11\", \"salary\":\"Fiona Green\"},\r\n"
				+ "{\"id\":30, \"name\":\"Shou Itou\", \"position\":\"Regional Marketing\", \"office\":\"Tokyo\", \"extension\":\"8899\", \"startDate\":\"2011/08/14\", \"salary\":\"Shou Itou\"},\r\n"
				+ "{\"id\":30, \"name\":\"Michelle House\", \"position\":\"Integration Specialist\", \"office\":\"Sidney\", \"extension\":\"2769\", \"startDate\":\"2011/06/02\", \"salary\":\"Michelle House\"},\r\n"
				+ "{\"id\":32, \"name\":\"Suki Burks\", \"position\":\"Developer\", \"office\":\"London\", \"extension\":\"6832\", \"startDate\":\"2009/10/22\", \"salary\":\"Suki Burks\"},\r\n"
				+ "{\"id\":33, \"name\":\"Prescott Bartlett\", \"position\":\"Technical Author\", \"office\":\"London\", \"extension\":\"3606\", \"startDate\":\"2011/05/07\", \"salary\":\"Prescott Bartlett\"},\r\n"
				+ "{\"id\":34, \"name\":\"Gavin Cortez\", \"position\":\"Team Leader\", \"office\":\"San Francisco\", \"extension\":\"2860\", \"startDate\":\"2008/10/26\", \"salary\":\"Gavin Cortez\"},\r\n"
				+ "{\"id\":35, \"name\":\"Martena Mccray\", \"position\":\"Post-Sales support\", \"office\":\"Edinburgh\", \"extension\":\"8240\", \"startDate\":\"2011/03/09\", \"salary\":\"Martena Mccray\"},\r\n"
				+ "{\"id\":36, \"name\":\"Unity Butler\", \"position\":\"Marketing Designer\", \"office\":\"San Francisco\", \"extension\":\"5384\", \"startDate\":\"2009/12/09\", \"salary\":\"Unity Butler\"}\r\n"
				+ "]\r\n"
				+ "";
		
		return returnDate;
	}
	@RequestMapping(value = "/labourcomplaint/getlabourcomplaint", method = RequestMethod.GET)
	public String getLabourcomplaint(@Validated User user, Model model) {
		
		String returnDate="[{\"compliant_no\":\"Hari\",\"compliant_date\":\"Hari\",\"compliant_name\":\"Hari\",\"sex\":\"Male\",\"passport_number\":\"123\",\"place_of_issue\":\"loc1\",\"date_of_birth\":\"1984\",\"civil_id_number\":\"12345\",\"age\":\"43\",\"status_of_e_migrate\":\"abcd\",\"address_in_India\":\"india\",\"contant_person_kuwait\":\"abcd\",\"arival_date_in-kuwait\":\"2021\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"balu\",\"compliant_date\":\"balu\",\"compliant_name\":\"kumar\",\"sex\":\"Male\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"kumar\",\"compliant_date\":\"kumar\",\"compliant_name\":\"bual\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"murali\",\"compliant_date\":\"murali\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"vishal\",\"compliant_date\":\"Vishal\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"sri\",\"compliant_date\":\"sri\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"kishore\",\"compliant_date\":\"kishore\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"vishnu\",\"compliant_date\":\"vishnu\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"murali\",\"compliant_date\":\"murali\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"vishnu\",\"compliant_date\":\"vishal\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"},\r\n"
				+ "{\"compliant_no\":\"lak\",\"compliant_date\":\"2021\",\"compliant_name\":\"Hari\",\"sex\":\"Hari\",\"passport_number\":\"Hari\",\"place_of_issue\":\"Hari\",\"date_of_birth\":\"Hari\",\"civil_id_number\":\"Hari\",\"age\":\"Hari\",\"status_of_e_migrate\":\"Hari\",\"address_in_India\":\"Hari\",\"contant_person_kuwait\":\"Hari\",\"arival_date_in-kuwait\":\"Hari\",\"agent_details\":\"Hari\",\"name\":\"Hari\",\"adress\":\"Hari\",\"tel_no\":\"Hari\",\"Amount_paid\":\"Hari\",\"name_of_company\":\"Hari\",\"status_of_residency\":\"Hari\",\"date_of_expiry\":\"Hari\",\"date_on_whci_worker\":\"Hari\",\"case_field\":\"Hari\",\"reason_for_not_fillinf_case\":\"Hari\",\"status_of_any_case\":\"Hari\",\"details_of_compliant\":\"Hari\",\"promissed_job\":\"Hari\",\"actual_job_given\":\"Hari\",\"promissed_salary_kd\":\"Hari\",\"actual_salary_kd\":\"Hari\",\"pending_salary\":\"hari\"}\r\n"
				+ "]";
		
		return returnDate;
	}
	@RequestMapping(value = "/getallUsers2", method = RequestMethod.POST)
	public String getallUsers2(@Validated User user, Model model) {
		String returnValue="{\"id\":1, \"name\":\"Name modified by server\", \"position\":\"Modified position\", \"office\":\"\", \"extension\":\"\", \"startDate\":\"\", \"salary\":\"\"}";
	return returnValue;
	}
	
	
}
